### ISSUE TITLE
Add a "fullscreen" option

### ISSUE THREAD

**Issue by cdcharlebois** [cdcharlebois/AutoCompleteForMendix#4]
This fullscreen option should combine the fix from #1, and trigger different styling rules based on this: 
```css
.select2-dropdown{
   height: 100vh !important;
   width: 100vw !important;
   position:fixed;
   top:0;
   left:0
}

.select2-results__options {
   max-height: none !important;
}
```
